name: rssbot
debug: true
# local: true # local mode(do not send telegram message)
interval: 300 # seconds
# proxy: https://localhost:1080/ # proxy (Optional)
template: | # message template
  {name}
  {title}
  Updated: {updated}
  Author: {author}
  [Read More]({link})
telegram:
  access_token: 111111:AAAAAAAAAAAAAAA # your telegram bot access token
  default_chat_id: '123456789' # your telegram chat id
  parse_mode: Markdown # null || 'Markdown' || 'HTML' see: https://core.telegram.org/bots/api#html-style
subscriptions:
  - name: rssbot commit
    url: https://github.com/lawvs/rssbot/commits/master.atom
    # filter_title: feat # filter title
